export const AUTHENTICATE = "AUTHENTICATE";
export const LOG_OUT = "LOG_OUT";
export const SET_PROFILE_INFO = "SET_PROFILE_INFO";

export const SET_ERROR = 'SET_ERROR';
export const CONFIRM_ERROR = 'CONFIRM_ERROR';

export const LOADER_OPEN = 'LOADER_OPEN';
export const LOADER_CLOSE = 'LOADER_CLOSE';

export const SET_LOADING = 'SET_LOADING';
export const BUSINESS_GETS = 'BUSINESS_GETS';
export const BUSINESS_STATUS_CHANGE = 'BUSINESS_STATUS_CHANGE';

export const SET_STORES = 'SET_STORES';
export const SET_STORE = 'SET_STORE';
export const CHANGE_STORE_STATUS = 'CHANGE_STORE_STATUS';

export const SET_USERS = 'SET_USERS';
export const SET_USER = 'SET_USER';
export const CHANGE_USER_STATUS = 'CHANGE_USER_STATUS';

export const BUSINESS_DDL_LOADING = 'BUSINESS_DDL_LOADING';
export const BUSINESS_DDL_SET_DATA = 'BUSINESS_DDL_SET_DATA';

export const STORE_DDL_LOADING = 'STORE_DDL_LOADING';
export const STORE_DDL_SET_DATA = 'STORE_DDL_SET_DATA';
